import type { DecisionFieldKey } from "../decision-record";

/** GOLD sample page mapping. Every renderer consumes the same record fields. */
export const GOLD_SECTIONS: ReadonlyArray<{id:string; title:string; subtitle:string; fields:DecisionFieldKey[]}> = [
 {id:"01",title:"Acquisition Decision Record",subtitle:"Evaluated asset, position and decision",fields:["identity.api10","identity.api14","identity.county","identity.tract","identity.evaluated_position","identity.interest_scope","decision.posture","economics.base_value","economics.evidence_adjusted_value","economics.measured_exposure","ownership.net_mineral_acres","ownership.nri","decision.confidence","decision.closing_readiness","economics.asking_price"]},
 {id:"02",title:"Value and price",subtitle:"Commodity and ownership effects kept separate",fields:["economics.base_value","economics.measured_exposure","economics.evidence_adjusted_value","economics.downside_value","economics.upside_value","economics.maximum_buy_price","economics.risk_adjusted_value","economics.discount_rate","economics.minimum_margin","economics.horizon","economics.price_deck"]},
 {id:"03",title:"Decision sensitivity",subtitle:"What can change the decision",fields:["economics.sensitivity","economics.asking_price","economics.minimum_margin","title.scenarios"]},
 {id:"04",title:"Risk map",subtitle:"Measured exposure and unpriceable evidence gaps",fields:["title.exceptions","title.encumbrances","economics.measured_exposure"]},
 {id:"05",title:"Scenario comparison",subtitle:"Ownership and commodity scenarios on separate axes",fields:["title.scenarios","ownership.mineral_fraction","ownership.net_mineral_acres","ownership.nri","economics.base_value","economics.downside_value","economics.upside_value"]},
 {id:"06",title:"Confidence and closing readiness",subtitle:"Independent states with explicit evidence limits",fields:["decision.confidence","decision.closing_readiness","title.exceptions","decision.posture"]},
 {id:"07",title:"How the decision is produced",subtitle:"Source evidence, engine derivations and decision rules",fields:["decision.rule_trace","identity.lease","identity.operator","identity.district"]},
 {id:"08",title:"Production and forecast",subtitle:"Subject-well and lease reporting scopes are kept distinct",fields:["production.subject_monthly","production.lease_monthly","production.subject_ttm_oil","production.subject_ttm_gas","production.subject_yoy_decline","forecast.next12_oil","forecast.remaining_oil","forecast.remaining_gas","forecast.method"]},
 {id:"09",title:"Subsurface and development geometry",subtitle:"Only evidenced measurements or named derivations",fields:["geology.latitude","geology.longitude","geology.map_symbol","geology.survey","geology.formation","geology.tvd","geology.tvdss","geology.net_pay","geology.porosity","geology.water_saturation","geology.pressure_gradient","geology.net_to_gross","geology.parent_child","geology.same_bench_spacing","geology.interference","geology.wells_per_section","geology.lateral_length","geology.completion_stages","geology.proppant","geology.fluid"]},
 {id:"10",title:"How ownership was derived",subtitle:"Reviewed instruments and exact fractions",fields:["title.ownership_graph","ownership.mineral_fraction","ownership.gross_acres","ownership.net_mineral_acres","identity.evaluated_position"]},
 {id:"11",title:"Regulatory standing",subtitle:"Retrieved records do not imply a complete or current search",fields:["regulatory.operator_standing","regulatory.compliance","regulatory.severance","regulatory.orphan","regulatory.plugging","regulatory.injection","regulatory.imaged_documents","regulatory.permits"]},
 {id:"12",title:"Title becomes dollars",subtitle:"Ownership, allocation, royalty and economic assumptions",fields:["ownership.mineral_fraction","ownership.gross_acres","ownership.net_mineral_acres","ownership.unit_acres","ownership.tract_participation","ownership.lease_royalty","ownership.nri","economics.base_value","economics.costs","economics.tax_assumptions"]},
 {id:"13",title:"Audit trail",subtitle:"Source to fact to derivation to output",fields:["identity.well_name","identity.field","decision.rule_trace"]},
 {id:"14",title:"Unpriced exceptions and confidence",subtitle:"Unknown impact is not zero impact",fields:["title.encumbrances","title.exceptions","production.variance_pct","production.variance_threshold","decision.confidence"]},
 {id:"15",title:"Decision and closing rule trace",subtitle:"Explicit evaluation outcomes and missing prerequisites",fields:["decision.posture","decision.closing_readiness","decision.rule_trace"]},
 {id:"A",title:"Evidence appendix",subtitle:"Instruments and search boundaries",fields:["title.instruments","title.search_scope"]},
 {id:"A1",title:"Source reconciliation",subtitle:"Independent well-level and regulator lease evidence",fields:["production.vendor_lease_sum","production.regulator_lease_total","production.variance_pct","production.variance_threshold"]},
 {id:"A2",title:"Source inventory and coverage",subtitle:"Retained sources, timestamps, scope and retrieval failures",fields:[]},
];
